apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-config
  namespace: monitoring
data:
  loki-config.yaml: |
    auth_enabled: false
    server:
      http_listen_port: 3100
      http_grpc_port: 9095
    distributor:
      ring:
        kvstore:
          store: inmemory
          consistency: strong
    storage_config:
      boltdb_shipper:
        active_index_directory: /tmp/loki/index
        cache_directory: /tmp/loki/cache
      filesystem:
        directory: /tmp/loki/chunks
    chunk_target_size: 1048576