apiVersion: v1
kind: Pod
metadata:
  name: grafana
  labels:
    app: grafana
  annotations:
    prometheus.io/scrape: "true"  # Active le scraping pour Grafana
    prometheus.io/port: "3000"     # Port à scruter pour Grafana
spec:
  containers:
    - name: grafana
      image: grafana/grafana
      ports:
        - containerPort: 3000
