apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  labels:
    app: grafana
spec:
  selector:
    app: grafana
  ports:
    - port: 8080       # Port externe du service
      targetPort: 3000  # Port du conteneur Grafana
  type: NodePort
