apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  labels:
    app: prometheus
spec:
  selector:
    app: prometheus
  ports:
    - port: 9090       # Port externe du service
      targetPort: 9090  # Port du conteneur Prometheus
  type: NodePort
