apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prometheus-binding
  namespace: default  # ou le namespace où Prometheus est déployé
subjects:
- kind: ServiceAccount
  name: default  # nom du service account
  namespace: default  # ou le namespace où Prometheus est déployé
roleRef:
  kind: Role
  name: prometheus
  apiGroup: rbac.authorization.k8s.io
