apiVersion: v1
kind: Pod
metadata:
  name: prometheus
  labels:
    app: prometheus
spec:
  containers:
    - name: prometheus
      image: prom/prometheus
      ports:
        - containerPort: 9090
      args:
        - "--config.file=/etc/prometheus/prometheus.yml"  # Indique où trouver le fichier de config
      volumeMounts:
        - name: prometheus-config-volume
          mountPath: /etc/prometheus  # Point de montage du ConfigMap
  volumes:
    - name: prometheus-config-volume
      configMap:
        name: prometheus-config  # Nom du ConfigMap
