# my global config
global:
  scrape_interval:     5s
  evaluation_interval: 5s

alerting:
  alertmanagers:
  - static_configs:
    - targets:

rule_files:

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090']

  - job_name: 'cadvisor'
    static_configs:
    - targets: ['cadvisor:8080']
  - job_name: 'grafana'
    static_configs:
    - targets: ['grafana-service:3000']