apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default  # ou le namespace où Prometheus est déployé
  name: prometheus
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
