apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
data:
  filebeat.yml: |
    filebeat.inputs:
    - type: log
      enabled: true
      paths:
        - /var/log/pods/*/*.log  # Chemin vers les logs des pods

    output.logstash:
      hosts: ["logstash:5044"]