apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-config
data:
  logstash.conf: |
    input {
      beats {
        port => 5044
      }
    }
    output {
      elasticsearch {
        hosts => ["http://elasticsearch:9200"]
        index => "logs-%{+YYYY.MM.dd}"
        user => "elastic"  # Utilisateur pour se connecter à Elasticsearch
        password => "toto"  # Remplacez par le mot de passe réel
      }
    }