name: CI/CD Pipeline

on:
  push:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image 1
        run: |
          docker build -t emivelle/monapp1 .dockerfile

      - name: Build Docker image 2
        run: |
          docker build -t emivelle/monapp2 .dockerfile2

      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Publish Docker Image 1
        run: |
          docker push emivelle/monapp1

      - name: Publish Docker Image 2
        run: |
          docker push emivelle/monapp2
